### PR TITLE
TwitGet now able to log in

### PR DESCRIPTION
**Pull request by ImportTaste**
I got an email from Twitter asking 'Is this you?' and I checked out temp.html, it's working. Hopefully this helps.

### CODE REVIEW

**Comment by ImportTaste** [comment]
This isn't Python, but may give you clues on how to properly download all .jpg-orig files from a user's entire twitter history, I use this extension a lot.

https://github.com/furyutei/twMediaDownloader/blob/master/src/js/twMediaDownloader.user.js

**Comment by ImportTaste** [comment]
@fake-name I saw in the issue I posted that you didn't see it, do you have alerts off unless you're pinged?

**Comment by fake-name** [comment]
> do you have alerts off?

Yep. I somehow did. No idea how.

**Comment by fake-name** [comment]
Honestly, twitter is so garbage I personally probably won't do anything with logging in. As long as you can *see* mature tweets without login (which you currently can), something like https://github.com/bisguzar/twitter-scraper sounds like a much better approach to the issue.

**Comment by ImportTaste** [comment]
I think the issue involves the search. In order to facilitate scraping at a decent speed, the use of 'until' and 'since' are used to move down a user's timeline. (Other search operators, if you're interested, are [here](https://github.com/igorbrigadir/twitter-advanced-search).)

And, for whatever reason, tweets marked as sensitive content are hidden from the search results unless you have an account with the 'Hide sensitive content' option _disabled_ in the Search Settings. It could be that this can be changed in the cookie without having an account, but I doubt it.

Without using search, that means to scrape a user's tweets for media, it has to start from the beginning every time, and as it moves further and further down the timeline, it gets slower and slower and slower to the point it might even stall and you'll have to try again.

For users that don't have a huge tweet history, this isn't a big deal. But artists that have been tweeting art since 2015, it's a big problem.

**Comment by fake-name** [comment]
> But for artists that have been tweeting art since 2015, it's a big problem.

I mean, I'd want to fetch all that content *anyways*, so that's not a huge deal.

AIUI (based on maybe 2 minutes of looking), https://github.com/bisguzar/twitter-scraper doesn't use search facilities, but rather emulates how the JS twitter client works. Since you can view sensitive stuff there, I assume you can get to it via twitter-scraper.

**Comment by ImportTaste** [comment]
>I mean, I'd want to fetch all that content anyways, so that's not a huge deal.

I'm afraid it is, because if an artist has enough tweets, it simply won't make to the end (or rather the beginning), and may even skip tweets FNAR.

When I say it slows down the more tweets it has to load, I mean it really, really, REALLY slows down. Glacial. And then it will start timing out.

**Comment by ImportTaste** [comment]
Any progress on the scraper? It certainly looks daunting. But even with the extension I linked, it's extremely tedious to keep the twitters up to date. And I ended up missing out on a month and a half of art from an artist's account getting nuked for some arbitrary reason, as twitter does.

**Comment by fake-name** [comment]
I'm slammed at work at the moment, so no.

**Comment by ImportTaste** [comment]
I swear to god if you don't do this soon I'm going to hack your Club Penguin account.

**Comment by fake-name** [comment]
GLHF, I guess. I'm on vacation for the next week.

**Comment by ImportTaste** [comment]
damnit

**Comment by fake-name** [comment]
Ok, yeah, if we're going to login to twitter, it should be done via the proper channels (e.g. OAuth API access).

**Comment by fake-name** [comment]
Holy fuck, they require a phone number for getting proper API access.

Fuck that noise so much.

**Comment by ImportTaste** [comment]
@fake-name I can help you out with that. Emailing you.

**Comment by fake-name** [comment]
It's more I'm offended by the fact that they **require** a phone number rather then anything else.

**Comment by ImportTaste** [comment]
That's just about every online service now. GitHub will start asking you for one soon enough. Ain't the future great?

**Pull request merged**
