### PR TITLE
Add IPython requirement

### PR DESCRIPTION
**Pull request by ImportTaste**
Mmyup

### CODE REVIEW

**Comment by fake-name** [comment]
I pushed the import down to the exception handler. It's just for me to debug a failure state, so if someone doesn't have ipython it'd have failed anyways.

**Comment by ImportTaste** [comment]
Is this error related?
```
[18/Aug/2020:09:35:00] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\cheroot\server.py", line 1795, in serve
    self.tick()
  File "C:\Python38\lib\site-packages\cheroot\server.py", line 2030, in tick
    self.connections.expire()
  File "C:\Python38\lib\site-packages\cheroot\connections.py", line 107, in expire
    for sock_fd, conn in timed_out_connections:
  File "C:\Python38\lib\site-packages\cheroot\connections.py", line 102, in <genexpr>
    timed_out_connections = (
  File "C:\Python38\lib\_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: dictionary changed size during iteration

cherrypy.error - ERROR - [18/Aug/2020:09:35:00] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\cheroot\server.py", line 1795, in serve
    self.tick()
  File "C:\Python38\lib\site-packages\cheroot\server.py", line 2030, in tick
    self.connections.expire()
  File "C:\Python38\lib\site-packages\cheroot\connections.py", line 107, in expire
    for sock_fd, conn in timed_out_connections:
  File "C:\Python38\lib\site-packages\cheroot\connections.py", line 102, in <genexpr>
    timed_out_connections = (
  File "C:\Python38\lib\_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: dictionary changed size during iteration
```
Started getting this today, and the only thing I can think of is that I recently reinstalled Python and didn't install IPython.

**Comment by fake-name** [comment]
That's unrelated, though weird. 

Cheroot is the server component of CherryPy. From the look of it, this is it's internal time-out handler being confused by a connection being added/removed while it's scanning to close any connections that have timed out.

It should probably be reported upstream, but I'd ignore it unless it actually seems to break something.

**Comment by ImportTaste** [comment]
> That's unrelated, though weird.
> 
> Cheroot is the server component of CherryPy. From the look of it, this is it's internal time-out handler being confused by a connection being added/removed while it's scanning to close any connections that have timed out.
> 
> It should probably be reported upstream, but I'd ignore it unless it actually seems to break something.

Well I mean, it might be breaking something. I don't actually use the web server at all, I only start it up when I need to add artists and then I close it.

**Comment by fake-name** [comment]
I think the only issue it could cause would be idle connections taking a little longer to time out.

**Pull request closed without merging**
