### PR TITLE
Tweak dump JSON output

### PR DESCRIPTION
**Pull request by ImportTaste**
The filename seems to contain an important art ID that isn't anywhere else, so I want it in its own index.

### CODE REVIEW

**Comment by fake-name** [comment]
I can never remember how much I need to nest list comprehensions to make them something I can pass about. Apparently I thought one more then is actually remembered.

**Comment by fake-name** [comment]
Note that that patch will throw away any additional filenames, if a single post has more then one associated file. Actually, it'll also explode for items without any associated content.

**Comment by fake-name** [comment]
Since I'm already exporting the item file contents, I just put the fspath in with the rest of it. Actually, it's kind of embarrassing I forgot it in the first place. Gah.

**Comment by ImportTaste** [comment]
The entire reason I made this PR was to take fspath out of that list so it's on its own key for easier parsing with PowerShell.

**Pull request merged**
